sudo: false
language: cpp
matrix:
  include:
      #linux
      - os: linux
        services: docker
        script:
          - ./archive.sh
          - docker build -f scripts/docker/debian/Dockerfile-stretch .
      - os: linux
        services: docker
        script:
          - ./archive.sh
          - docker build -f scripts/docker/debian/Dockerfile-jessie .
      - os: linux
        sudo: required
        before_install:
          - ./scripts/dependencies-ubuntu.sh
        install: true
        script:
          - ./scripts/install-ubuntu.sh
      - os: linux
        sudo: required
        before_install:
          - ./scripts/dependencies-ubuntu.sh
        install: true
        script:
          - ./scripts/debuild.sh
      #cross compile windows
      - os: linux
        services: docker
        script:
          - ./archive.sh
          - travis_wait 60 docker build -f scripts/docker/windows-crosscompile/Dockerfile-wheezy .
      - os: linux
        services: docker
        script:
          - ./archive.sh
          - travis_wait 60 docker build -f scripts/docker/windows-crosscompile/Dockerfile-xenial .
      - os: linux
        services: docker
        script:
          - ./archive.sh
          - travis_wait 60 docker build -f scripts/docker/windows-crosscompile/Dockerfile-trusty .
      - os: linux
        sudo: required
        before_install:
          - cd $TRAVIS_BUILD_DIR/scripts/windows-crosscompile
          - pwd && ls -al
          - travis_wait 60 ./dependencies.sh
          - cd $TRAVIS_BUILD_DIR
        install: true
        script:
          - travis_wait 60 ./scripts/windows-crosscompile/compile-peercoin.sh
      #osx     
      - os: osx
        osx_image: xcode9.2
        before_script:
          - ./scripts/dependencies-osx.sh 
        script:
          - ./scripts/install-osx.sh

